"""omans

Revision ID: 2348730e1024
Revises: ed55bd52a6c0
Create Date: 2023-12-12 11:10:30.419129

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2348730e1024'
down_revision = 'ed55bd52a6c0'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
