"""Add all tables

Revision ID: 861cf190bf40
Revises: 649c75d9fdf4
Create Date: 2023-12-12 10:11:30.739221

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '861cf190bf40'
down_revision = '649c75d9fdf4'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
