"""tables

Revision ID: ed55bd52a6c0
Revises: 861cf190bf40
Create Date: 2023-12-12 10:20:43.335487

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ed55bd52a6c0'
down_revision = '861cf190bf40'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
